USE LIVROS;

CREATE TABLE IF NOT EXISTS PRODUTOS (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, NOME VARCHAR(150) NOT NULL, AUTOR VARCHAR(100) NOT NULL, GENERO VARCHAR(15) NOT NULL, NACIONALIDADE VARCHAR(25) , PAGINAS INT NOT NULL, PRECO FLOAT NOT NULL);

CREATE TABLE IF NOT EXISTS CLIENTES (
CPF_CLIENTE VARCHAR(11) PRIMARY KEY NOT NULL,
NOME_CLIENTE VARCHAR(255),
IDADE_CLIENTE INT, 
SEXO_CLIENTE VARCHAR(1) NULL
);

CREATE TABLE IF NOT EXISTS AVALIACAO 
(
ID_AVALIACAO INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
TITULO_AVALIACAO VARCHAR(50), 
DATA_AVALIACAO DATE,
NOTA VARCHAR(5),
COMENTARIOS VARCHAR(200),
ID_PRODUTO INT,
CPF_CLIENTE VARCHAR(11)
)  


